### ISSUE TITLE
Make conf.ini into env variables.

### ISSUE THREAD

**Issue by jbygdell** [NBISweden/LocalEGA-helm#2]
All connection targets need to be set via helm variables.

**Comment by blankdots** [comment]
Probably worth pointing here: https://localega.readthedocs.io/en/latest/setup.html#configuration and here: https://github.com/NBISweden/LocalEGA/wiki/Configuration-Settings-%7C-Environment-Variables

All variables in `conf.ini` can be set as env variables:
> from environment variables (where the naming convention is uppercase section_option (as in default.ini), e.g. VAULT_DRIVER or POSTGRES_DB,

**Comment by jbygdell** [comment]
This would be easier if the documentation where up to date.
