### ISSUE TITLE
Local Persistent Volumes Option for Deployment

### ISSUE THREAD

**Issue by blankdots** [NBISweden/LocalEGA-helm#22]
### Description
We will be using POSIX file system for kubernetes and the helm charts deployment would be nice if it supports it.
Useful resource: https://kubernetes.io/blog/2018/04/13/local-persistent-volumes-beta/

We (CSC) might be able to spin the environment for running the end to end tests.

### Definition of Done
Helm charts provides option for persistence local system.

### How to test
End to end test pass with File System as backend.

**Comment by jonandernovella** [comment]
I would like to make two important points with regards to this:

1) PVs are nowadays provisioned using Storage Classes, which have no place in Helm Charts, but should be setup by a sysadmin in the corresponding cluster. The only thing you need to do in the chart should be defining the class name in the app deployment stage.

2) This new feature about local PVs is still "far" from being production ready.

**Comment by blankdots** [comment]
@jonandernovella any suggestions for how we can leverage FileSystem for `Inbox` and `Archive`, as in our deployments we (most likely) are not going to use S3. We can make use, of course, of `hostPath` or have our own S3 deployed with the System and have some persistent storage with that, but we think that from a performance standpoint the right way to go is to make use of FileSystem as persistent storage.

**Comment by jonandernovella** [comment]
@blankdots Apparently starting from Kubernetes `v1.14` the `local` volume feature state has become stable. Source: https://kubernetes.io/docs/concepts/storage/volumes/#local. Note this version was released just a few days ago.

**Comment by jonandernovella** [comment]
Here some important notes from the docs:

> Local volumes are still subject to the availability of the underlying node and are not suitable for all applications. If a node becomes unhealthy, then the local volume will also become inaccessible, and a Pod using it will not be able to run. Applications using local volumes must be able to tolerate this reduced availability, as well as potential data loss, depending on the durability characteristics of the underlying disk.

**Comment by blankdots** [comment]
hmm, maybe we go back to our initial idea of glusterFS.

**Comment by jbygdell** [comment]
There is another yet untested method, use an NFS server for the shared filesystem.

**Comment by blankdots** [comment]
yes true, but I think it will all boil down to performance, once I finish the load +/- stress tests that will give some indication of what we will go with in our deployments.
