### ISSUE TITLE
S3 secrets mismatch

### ISSUE THREAD

**Issue by jonandernovella** [NBISweden/LocalEGA-helm#30]
### Expected Behavior

S3 secrets should both contain the same contents.
### Current Behavior

```
kubectl describe secret localega-s3-keys -n lega
Name:         localega-s3-keys
Namespace:    lega

s3_access_key:  16 bytes
s3_secret_key:  32 bytes

kubectl describe secret myminio -n lega
Name:         myminio
Namespace:    lega

accesskey:  18 bytes
secretkey:  34 bytes 

```

Interestingly, `myminio` secret is including the `""` around the actual secret.

### Possible Solution

The latest Minio Helm chart seems to be broken.  We might need to downgrade or fix a version in our deployments.

### Context (Environment)

Cluster deployed using `rke-openstack` and `legainit`

``` $helm list 
NAME   	REVISION	UPDATED                 	STATUS  	CHART         	APP VERSION                 	NAMESPACE
cega   	1       	Mon Apr 15 16:24:32 2019	DEPLOYED	cega-0.1.2    	1.0                         	cega     
lega   	1       	Mon Apr 15 16:24:34 2019	DEPLOYED	localega-0.2.3	1.0                         	lega     
myminio	1       	Mon Apr 15 16:24:25 2019	DEPLOYED	minio-2.4.12  	RELEASE.2019-04-09T01-22-30Z	lega 
```

**Comment by blankdots** [comment]
did you start minio using: 
```
helm install --set accessKey=S3_access,secretKey=S3_secret,minioConfig.region=S3_region stable/minio
```
or somehow else?

**Comment by jonandernovella** [comment]
@blankdots Last time I deployed (with the previous version of legainit) I did that very same command but putting the quotation marks around the access key and secrets, and it worked. It seems that currently the quotation marks are not read by the `localega` secret.

**Comment by jonandernovella** [comment]
Will need to change my deployment script to skip using the quotation marks. Thanks @blankdots !!
