### ISSUE TITLE
cega-mq does not start

### ISSUE THREAD

**Issue by jonandernovella** [NBISweden/LocalEGA-helm#31]
### Expected Behavior

cega-mq should successfully mount the necessary volumes and start accordingly
### Current Behavior

``` 
lega-se-testy-service-000  MountVolume.SetUp failed for volume "temp"
 : configmap references non-existent config key: cega.config

lega-se-testy-service-000  Unable to mount volumes for pod:timeout expired waiting for
 volumes to attach or mount for pod "cega"/"cega-mq-7845f789d6-l79qj". list of unmounted
 volumes=[temp]. list of unattached volumes=[cega-mq-entrypoint temp rabbitmq 
 default-token-lnzxx]
``` 
### Context (Environment)

`rke-openstack` + `legainit`

**Comment by blankdots** [comment]
@jonandernovella I assume you use https://github.com/NBISweden/LocalEGA-deploy-init and you copy the generated `cega.json` in `conf` folder of `ega-charts` https://github.com/NBISweden/LocalEGA-helm/blob/master/ega-charts/cega/templates/cega-cm.yaml#L11 ?

**Comment by jonandernovella** [comment]
@blankdots Correct! There is no inconsistencies that I can find....

**Comment by blankdots** [comment]
I will try to replicate tomorrow and see what I get.

**Comment by jonandernovella** [comment]
@blankdots Fixed after changing the deployment script according to the travis test. I was only copying cega.json, which was not enough.
