### ISSUE TITLE
Add TLS option to the chart

### ISSUE THREAD

**Issue by jbygdell** [NBISweden/LocalEGA-helm#32]
### Definition of Done

TLS certificates are deployed an used by the containers.

**Comment by jbygdell** [comment]
WIP

**Comment by jonandernovella** [comment]
Is this going to be done in the form of a boolean check for each of the services? Or do we want to have a single variable to enforce TLS on all services?

**Comment by jbygdell** [comment]
Have a look in the `feature/tls` branch.
